version: '3.8'

services:
  nginx:
    image: nginx
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    env_file:
      - .env

  mariadb:
    image: mariadb
    build: ./requirements/mariadb
    container_name: mariadb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    env_file:
      - .env
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always

  wordpress:
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/html
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception
    env_file:
      - .env

networks:
  inception:
    name: inception
    driver: bridge

volumes:
  mariadb:
    name: mariadb
    driver_opts:
      type: none
      o: bind
      device: /home/cgerling/data/mariadb
  wordpress:
    name: wordpress
    driver_opts:
      type: none
      o: bind
      device: /home/cgerling/data/wordpress

