version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    restart: always

  nginx:
    build: ./requirements/nginx
    restart: always

  wordpress:
    build: ./requirements/wordpress
    restart: always
